//
//  CellFooter.swift
//
//  Created on 16/06/2017.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class CellFooter: NSObject {
    
    
    //MARK: - Canvas Drawings
    
    /// Page 1
    
    class func drawCellFooter(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 375, height: 191), resizing: ResizingBehavior = .aspectFit) {
        /// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        /// Resize to Target Frame
        context.saveGState()
        let resizedFrame = resizing.apply(rect: CGRect(x: 0, y: 0, width: 375, height: 191), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 375, y: resizedFrame.height / 191)
        
        /// Rectangle
        let rectangle = UIBezierPath()
        rectangle.move(to: CGPoint(x: 0, y: 13.33))
        rectangle.addLine(to: CGPoint(x: 180, y: 13.33))
        rectangle.addLine(to: CGPoint(x: 189.5, y: 0))
        rectangle.addLine(to: CGPoint(x: 200, y: 13.33))
        rectangle.addLine(to: CGPoint(x: 375, y: 13.33))
        rectangle.addLine(to: CGPoint(x: 375, y: 163.68))
        rectangle.addLine(to: CGPoint(x: 302.18, y: 163.68))
        rectangle.addLine(to: CGPoint(x: 0, y: 163.68))
        rectangle.addLine(to: CGPoint(x: 0, y: 13.33))
        rectangle.close()
        rectangle.move(to: CGPoint(x: 0, y: 13.33))
        context.saveGState()
        context.translateBy(x: 0, y: 27.32)
        rectangle.usesEvenOddFillRule = true
        UIColor.white.setFill()
        rectangle.fill()
        context.saveGState()
        rectangle.lineWidth = 2
        context.beginPath()
        context.addPath(rectangle.cgPath)
        context.clip(using: .evenOdd)
        UIColor(white: 0.592, alpha: 1).setStroke()
        rectangle.stroke()
        context.restoreGState()
        context.restoreGState()
        
        context.restoreGState()
    }
    
    
    //MARK: - Canvas Images
    
    /// Page 1
    
    class func imageOfCellFooter() -> UIImage {
        struct LocalCache {
            static var image: UIImage!
        }
        if LocalCache.image != nil {
            return LocalCache.image
        }
        var image: UIImage
        
        UIGraphicsBeginImageContextWithOptions(CGSize(width: 375, height: 191), false, 0)
        CellFooter.drawCellFooter()
        image = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        LocalCache.image = image
        return image
    }
    
    
    //MARK: - Resizing Behavior
    
    enum ResizingBehavior {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.
        
        func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }
            
            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)
            
            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }
            
            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
    
    
}
